version: '3.9'

services:

  mysqlserver:
    image: mysql:latest
    container_name: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_product_service_network

  service-products:
    container_name: service-products
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlserver:3306/products?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    networks:
      - my_product_service_network

volumes:
  mysql_data:

networks:
  my_product_service_network:
    driver: bridge
    name: my_product_service_network
